apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workshop
  namespace: s6hina
spec:
  destination:
    namespace: s6hina
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argoCD/
    repoURL: https://github.com/naturalett/continuous-delivery
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
