apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: s6hina
spec:
  destination:
    name: in-cluster
    namespace: s6hina
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 45.6.0
    chart: kube-prometheus-stack

