apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.app_name_2 }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget }}
  selector:
    matchLabels:
       app: {{ .Values.labels.app }}