apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app_name_1 }}-secret
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgres.POSTGRES_PASSWORD }}  # Base64-encoded value for "password"