apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app_name }}-configmap
data:
  POSTGRES_USER: {{ .Values.postgres.POSTGRES_USER }}
  POSTGRES_DB: {{ .Values.postgres.POSTGRES_DB }}
  HOSTNAME: {{ .Values.postgres.HOSTNAME }}