{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "espresso-product.serviceAccountName" . }}
  labels:
    app: {{ .Values.labels.app }}
{{- end }}
